import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import React from "react";

import BreadcrumbNav from "../../common/breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    // <meta name="google-site-verification" content="eONIAiWLaZ_HYxHcKTUBuw8KDWH0SDyckup2RPcP4D0" />
    google: "eONIAiWLaZ_HYxHcKTUBuw8KDWH0SDyckup2RPcP4D0",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BreadcrumbNav />
        {children}
      </body>
    </html>
  );
}
